### ISSUE TITLE
AttributeError: 'IndoWordNet' object has no attribute 'morph'

### ISSUE THREAD

**Issue by VijayAshokGaikwad** [riteshpanjwani/pyiwn#9]
I am trying to use Morphological Analyzer of  IndoWordNet.
I am trying it for Hindi and Marathi language. 

First I executed following commands. 
from pyiwn import pyiwn
pyiwn.download()
iwn = pyiwn.IndoWordNet('hindi')
iwn.all_words()

All commands ran successfully. But when I used 
iwn.morph('some word in hindi')

it shows following error .
**AttributeError: 'IndoWordNet' object has no attribute 'morph'**

Can you please help.

**Comment by manojbalaji1** [comment]
This is because morph is not present in the IndoWordNet class
link: https://github.com/riteshpanjwani/pyiwn/blob/master/pyiwn/pyiwn.py

**Comment by riteshpanjwani** [comment]
@VijayAshokGaikwad Morphological Analyzer support is a little tricky to incorporate right now, I know it is mentioned in the GWC paper but that was not working as expected since that code is in Java and is available at https://www.cfilt.iitb.ac.in as a separate package, if you cannot download it, then, please email them. you can write a wrapper around that Java code to execute it in Python.
